### ISSUE TITLE
Prevent auto-pinning of active tab

### ISSUE THREAD

**Issue by aleclarson** [smallStall/auto-arrange-tabs#1]
If I have a tab pinned, this plugin will automatically pin my active tab after 8 seconds, which isn't something I want.

**Comment by smallStall** [comment]
Pinned tabs are no longer moved.
Please let me know if there is anything else, thanks.

![test](https://user-images.githubusercontent.com/91565962/193435887-aa44504b-7732-4ebf-b763-da9deb9273e9.gif)

**Comment by aleclarson** [comment]
Awesome work! Love the extension :+1:

**Comment by aleclarson** [comment]
Can you release it soon?

**Comment by smallStall** [comment]
Fixed version@0.4.0 has been released.
Can you please uninstall and then reinstall?

https://marketplace.visualstudio.com/items?itemName=smallStall.auto-arrange-tabs

**Comment by aleclarson** [comment]
Thanks! Btw, I tweeted about your extension.
https://twitter.com/retropragma/status/1577068559104024576

**Comment by smallStall** [comment]
Thank you for your tweet!
It's very encouraging.
